version: "3.1"
services:
  db:
    image: mongo:7.0.11
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  app:
    image: node:22.2.0
    depends_on:
      - db
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"

volumes:
  database:
